(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=768){cw++;}if(w>=960){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};!function(){if("Promise"in window){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},f=function(e){return e.target.closest("a")},p=function(t){var r=t.relatedTarget;r&&f(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},l={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=f(e);c(r)&&u(r.href)},l),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=f(r);c(n)&&(n.addEventListener("mouseout",p,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},l)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=960){var a='data-src';var e=document.querySelector('.js2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/codedevils-606-1.jpg':'images/codedevils-404-1.jpg'):'images/codedevils-202-1.jpg');
var a='data-src';var e=document.querySelector('.js3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/work-603-1.jpg':'images/work-402-1.jpg'):'images/work-201-1.jpg');
var a='data-src';var e=document.querySelector('.js4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/adult-chart-close-up-1043514-621.jpg':'images/adult-chart-close-up-1043514-414.jpg'):'images/adult-chart-close-up-1043514-207-1.jpg');
var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?'images/profile_pic-592.jpg':'images/profile_pic-296.jpg');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.js2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/codedevils-483.jpg':'images/codedevils-322.jpg'):'images/codedevils-161.jpg');
var a='data-src';var e=document.querySelector('.js3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/work-480.jpg':'images/work-320.jpg'):'images/work-160.jpg');
var a='data-src';var e=document.querySelector('.js4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/adult-chart-close-up-1043514-498.jpg':'images/adult-chart-close-up-1043514-332.jpg'):'images/adult-chart-close-up-1043514-166.jpg');
var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/profile_pic-744.jpg':'images/profile_pic-496.jpg'):'images/profile_pic-248.jpg');}else{var a='data-src';var e=document.querySelector('.js2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/codedevils-201.jpg':'images/codedevils-134.jpg'):'images/codedevils-67.jpg');
var a='data-src';var e=document.querySelector('.js3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/work-198.jpg':'images/work-132.jpg'):'images/work-66.jpg');
var a='data-src';var e=document.querySelector('.js4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/adult-chart-close-up-1043514-207.jpg':'images/adult-chart-close-up-1043514-138.jpg'):'images/adult-chart-close-up-1043514-69.jpg');
var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/profile_pic-384.jpg':'images/profile_pic-256.jpg'):'images/profile_pic-128.jpg');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
(function(){$('a[href^="#"]:not(.allowConsent,.noConsent,.denyConsent,.removeConsent)').each(function(i,e){$(e).click(function(){var t=e.hash.length>1?$('[name="'+e.hash.slice(1)+'"]').offset().top:0;return $("html, body").animate({scrollTop:t},400),!1})})})();
initMenu($('#m1')[0]);
initMenu($('#m2')[0]);
ldsrc('.js2');ldsrcset('.js13 source');ldsrc('.js3');ldsrcset('.js14 source');ldsrc('.js4');ldsrcset('.js15 source');var cs=new ConsentBanner('privacy-policy.html', undefined, 0);cs.start(1);
});